### ISSUE TITLE
API DMITEC Anfrage

### ISSUE THREAD

**Issue by Rainerwald** [Landeskompetenzzentrum-Forst-Eberswalde/FUK-DB#5]
- Terminabstimmung VK Sven Melzer von [DMITEC](https://shop.meier-nt.de/impressum)
- Fragen an DMITEC:
  - Möglichkeit der Lieferung von Maschinenlesbarer Daten (.csv, .xml)?
  -  Alternativen zur Herstellen einer API?

**Comment by b-lack** [comment]
Das passt gut, dann mache ich mich bis dahin zur Schnittstelle und möglichen Formaten.

**Comment by b-lack** [comment]
Offene Fragen wurden beantwortet!
